server:
  port: 8081
  servlet:
    session:
      timeout: 30m #30分钟，时间不能太短，否则测试不准

spring:
  application:
    name: hogwarts-mini
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hogwarts-mini?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hogwartsmini.demo.entity
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com.hogwartsmini.demo.dao: debug #打印sql


hogwarts:
  key1: hogwarts22